# Generated by Django 5.2.6 on 2025-10-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('installed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.office')),
            ],
            options={
                'db_table': 'tbl_device',
            },
        ),
        migrations.CreateModel(
            name='EnergyRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_energy_kwh', models.FloatField()),
                ('peak_power_w', models.FloatField()),
                ('carbon_emission_kgco2', models.FloatField()),
                ('cost_estimate', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device')),
            ],
            options={
                'db_table': 'tbl_energy_record',
            },
        ),
    ]
