# Generated by Django 5.2.6 on 2025-10-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_device',
            },
        ),
        migrations.CreateModel(
            name='EnergyRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_energy_kWh', models.FloatField()),
                ('peak_power_W', models.FloatField()),
                ('carbon_emission_kgCO2', models.FloatField()),
                ('cost_estimate', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device')),
            ],
            options={
                'db_table': 'tbl_energy_record',
            },
        ),
    ]
