# Generated by Django 5.2.6 on 2025-10-05 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_rename_role_office_department'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='adminpanel.office'),
        ),
    ]
