# Generated by Django 5.2.7 on 2025-10-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='sensors.device')),
            ],
            options={
                'db_table': 'tbl_sensor_reading',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='tbl_sensor__device__3e1034_idx'), models.Index(fields=['device', 'created_at'], name='tbl_sensor__device__4e46f8_idx'), models.Index(fields=['timestamp'], name='tbl_sensor__timesta_d1692b_idx')],
            },
        ),
    ]
