# Generated by Django 5.2.6 on 2025-12-11 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensorreading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='tbl_sensor__device__3e1034_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='tbl_sensor__timesta_d1692b_idx',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', 'date'], name='tbl_sensor__device__bf8a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['date'], name='tbl_sensor__date_be5841_idx'),
        ),
    ]
