# Generated by Django 5.2.6 on 2025-10-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_device_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
