# Generated by Django 5.2.6 on 2025-12-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensorreading_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='tbl_sensor__device__4e46f8_idx',
        ),
    ]
