# Generated by Django 5.2.6 on 2025-10-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='installed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
