# Generated by Django 5.2.6 on 2025-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_remove_device_name_device_installed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
