# Generated by Django 5.2.6 on 2025-12-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_remove_sensorreading_tbl_sensor__device__4e46f8_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='created_at',
        ),
        migrations.AddField(
            model_name='device',
            name='appliance_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='date',
            field=models.DateField(),
        ),
    ]
