# Generated by Django 5.2.6 on 2025-10-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_device_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energyrecord',
            old_name='total_energy_kWh',
            new_name='total_energy_kwh',
        ),
    ]
