# Generated by Django 5.2.6 on 2025-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_remove_sensorreading_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='appliance_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
