# Generated by Django 5.2.6 on 2025-10-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_rename_total_energy_kwh_energyrecord_total_energy_kwh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energyrecord',
            old_name='peak_power_W',
            new_name='peak_power_w',
        ),
    ]
