# Generated by Django 5.2.7 on 2025-12-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20251211_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='peak_power_w',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='total_energy_kwh',
            field=models.FloatField(default=0.0),
        ),
    ]
