# Generated by Django 5.2.6 on 2025-10-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_rename_peak_power_w_energyrecord_peak_power_w'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energyrecord',
            old_name='carbon_emission_kgCO2',
            new_name='carbon_emission_kgco2',
        ),
    ]
