# Generated by Django 5.2.7 on 2025-12-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_sensorreading_peak_power_w_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Settings',
            fields=[
                ('co2_id', models.AutoField(primary_key=True, serialize=False)),
                ('co2_emission_factor', models.FloatField(default=0.475)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_co2_settings',
            },
        ),
        migrations.CreateModel(
            name='CostSettings',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_per_kwh', models.FloatField(default=12.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_cost_settings',
            },
        ),
    ]
