# Generated by Django 5.2.6 on 2025-10-09 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_rename_carbon_emission_kgco2_energyrecord_carbon_emission_kgco2'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.office'),
        ),
    ]
