# Generated by Django 5.2.7 on 2025-12-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_co2settings_costsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co2settings',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='costsettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='co2settings',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costsettings',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
