# Generated by Django 5.2.6 on 2025-12-21 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_remove_co2settings_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSpike',
            fields=[
                ('spike_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('peak_power', models.FloatField()),
                ('baseline_power', models.FloatField()),
                ('spike_magnitude', models.FloatField()),
                ('duration_seconds', models.IntegerField(default=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device')),
            ],
            options={
                'db_table': 'tbl_power_spike',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='tbl_power_s_device__d51708_idx'), models.Index(fields=['timestamp'], name='tbl_power_s_timesta_ab18be_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('data_received', 'Data Received'), ('device_offline', 'Device Offline'), ('device_online', 'Device Online'), ('threshold_exceeded', 'Threshold Exceeded'), ('system_error', 'System Error'), ('spike_detected', 'Spike Detected')], max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.device')),
            ],
            options={
                'db_table': 'tbl_system_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'log_type'], name='tbl_system__timesta_fac4e7_idx'), models.Index(fields=['device', 'timestamp'], name='tbl_system__device__319d33_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklySpikeAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('spike_count', models.IntegerField(default=0)),
                ('max_spike_power', models.FloatField(default=0.0)),
                ('avg_baseline_power', models.FloatField(default=0.0)),
                ('spike_threshold', models.FloatField(default=0.0)),
                ('total_spike_duration_minutes', models.IntegerField(default=0)),
                ('interpretation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device')),
            ],
            options={
                'db_table': 'tbl_weekly_spike_analysis',
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'device')},
            },
        ),
    ]
