# Generated by Django 5.2.6 on 2026-01-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_powerspike_systemlog_weeklyspikeanalysis'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device', '-date'], name='tbl_sensor__device__147365_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['date', 'device'], name='tbl_sensor__date_a8dc8d_idx'),
        ),
    ]
