# Generated by Django 5.2.6 on 2026-01-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_sensorreading_tbl_sensor__device__147365_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('total_energy_kwh', models.FloatField(default=0)),
                ('peak_power_w', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('total_co2', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.device')),
            ],
            options={
                'db_table': 'tbl_energy_aggregation',
                'indexes': [models.Index(fields=['device', 'period_type', 'date'], name='tbl_energy__device__ded34f_idx'), models.Index(fields=['period_type', 'date'], name='tbl_energy__period__478895_idx')],
                'unique_together': {('device', 'date', 'period_type')},
            },
        ),
    ]
