# Generated by Django 5.2.7 on 2025-11-14 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('threshold_id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_efficient_max', models.FloatField(default=10.0)),
                ('energy_moderate_max', models.FloatField(default=20.0)),
                ('co2_efficient_max', models.FloatField(default=8.0)),
                ('co2_moderate_max', models.FloatField(default=13.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_threshold',
            },
        ),
    ]
