# Generated by Django 5.2.7 on 2025-11-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='co2_high_max',
            field=models.FloatField(default=18.0),
        ),
        migrations.AddField(
            model_name='threshold',
            name='energy_high_max',
            field=models.FloatField(default=30.0),
        ),
    ]
