# Generated by Django 5.2.6 on 2025-12-08 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_threshold_co2_high_max_threshold_energy_high_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_efficient_max', models.FloatField()),
                ('energy_moderate_max', models.FloatField()),
                ('energy_high_max', models.FloatField()),
                ('co2_efficient_max', models.FloatField()),
                ('co2_moderate_max', models.FloatField()),
                ('co2_high_max', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tbl_threshold_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
