# Generated by Django 5.2.6 on 2025-10-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_admin_created_at_admin_email_admin_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='role',
            new_name='department',
        ),
    ]
