# Generated by Django 5.2.6 on 2025-12-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_thresholdhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdhistory',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
