# Generated by Django 5.2.6 on 2025-10-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_rename_role_office_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='admin',
        ),
    ]
