# Generated by Django 5.2.6 on 2025-10-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_remove_office_admin'),
        ('sensors', '0009_alter_device_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
