# Generated by Django 5.2.6 on 2025-12-08 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_thresholdhistory_ended_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Threshold',
            fields=[
                ('threshold_id', models.AutoField(primary_key=True, serialize=False)),
                ('efficient_max', models.FloatField(default=8.0)),
                ('moderate_max', models.FloatField(default=13.0)),
                ('high_max', models.FloatField(default=18.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_co2_threshold',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyThreshold',
            fields=[
                ('threshold_id', models.AutoField(primary_key=True, serialize=False)),
                ('efficient_max', models.FloatField(default=10.0)),
                ('moderate_max', models.FloatField(default=20.0)),
                ('high_max', models.FloatField(default=30.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_energy_threshold',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ThresholdHistory',
        ),
    ]
