# Generated by Django 5.2.6 on 2025-12-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_co2threshold_energythreshold_delete_thresholdhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
