# Generated by Django 5.2.6 on 2025-12-10 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_delete_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='co2threshold',
            options={},
        ),
        migrations.AlterModelOptions(
            name='energythreshold',
            options={},
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='co2threshold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='co2threshold',
            name='efficient_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='co2threshold',
            name='high_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='co2threshold',
            name='moderate_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energythreshold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='energythreshold',
            name='efficient_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energythreshold',
            name='high_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energythreshold',
            name='moderate_max',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], default='info', max_length=20)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('target_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
