# Generated by Django 5.2.6 on 2025-12-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_co2threshold_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiNetwork',
            fields=[
                ('wifi_id', models.AutoField(primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_wifi_network',
                'ordering': ['priority', 'ssid'],
            },
        ),
    ]
